//! Data types describing a GUI background task: status, progress, the
//! invocation that started it and its log lines. Produced by
//! `super::TaskRunner` and read by the job and progress widgets.

use std::ffi::OsString;

/// Lifecycle state of a task.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum JobStatus {
    /// The child process is still running.
    Running,
    /// Exited with success.
    Completed,
    /// Exited with an error, failed to start or the worker vanished.
    Failed,
    /// Stopped by the user via [`super::TaskRunner::cancel`].
    Cancelled,
}

/// Progress of a running task as reported by the child's progress lines.
/// Either byte-based (`*_bytes`) or item-based (`*_items`); `None` means unknown.
#[derive(Debug, Clone, Default, PartialEq)]
pub(crate) struct TaskProgress {
    /// Bytes of work finished, capped at `total_bytes`.
    pub(crate) completed_bytes: Option<u64>,
    /// Bytes actually moved over the network (may differ from completed, e.g. skips).
    pub(crate) transferred_bytes: Option<u64>,
    /// Total bytes of the operation.
    pub(crate) total_bytes: Option<u64>,
    /// Average transfer rate since start, in bytes per second.
    pub(crate) bytes_per_second: Option<f64>,
    /// Estimated seconds until completion.
    pub(crate) eta_seconds: Option<u64>,
    /// Number of items finished so far.
    pub(crate) current_item: Option<usize>,
    /// Total number of items.
    pub(crate) total_items: Option<usize>,
}

impl TaskProgress {
    /// Completion ratio in `0.0..=1.0`: bytes when a byte total is known, else
    /// items; `None` when neither total is known. A zero total counts as done.
    /// Used by `widgets::progress_view` and the migration run step.
    pub(crate) fn fraction(&self) -> Option<f32> {
        if let Some(total) = self.total_bytes {
            if total == 0 {
                return Some(1.0);
            }
            let completed = self.completed_bytes.unwrap_or(0).min(total);
            return Some((completed as f64 / total as f64) as f32);
        }
        let total = self.total_items?;
        if total == 0 {
            return Some(1.0);
        }
        let completed = self.current_item.unwrap_or(0).min(total);
        Some(completed as f32 / total as f32)
    }
}

/// What was run, kept so a task can be shown or restarted.
#[derive(Debug, Clone)]
pub(crate) struct TaskInvocation {
    /// Display name of the task.
    pub(crate) task_name: String,
    /// CLI arguments after the global `--rclone` option.
    pub(crate) args: Vec<OsString>,
}

/// One task as shown in the GUI (current or last finished).
#[derive(Debug, Clone)]
pub(crate) struct TaskInfo {
    /// Display name.
    pub(crate) name: String,
    /// Quoted command line for display.
    pub(crate) command_preview: String,
    /// Current lifecycle state.
    pub(crate) status: JobStatus,
    /// Latest progress.
    pub(crate) progress: TaskProgress,
    /// Process exit code once finished; `None` while running or when unknown.
    pub(crate) exit_code: Option<i32>,
    /// How the task was started; `None` if not recorded.
    pub(crate) invocation: Option<TaskInvocation>,
}

impl TaskInfo {
    /// A freshly started task: `Running`, empty progress, no exit code.
    pub(crate) fn running(
        name: String,
        command_preview: String,
        invocation: TaskInvocation,
    ) -> Self {
        Self {
            name,
            command_preview,
            status: JobStatus::Running,
            progress: TaskProgress::default(),
            exit_code: None,
            invocation: Some(invocation),
        }
    }
}

/// Source of a log line.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum LogKind {
    /// Child standard output.
    Stdout,
    /// Child standard error (non-progress lines).
    Stderr,
    /// Message generated by the GUI itself (start failures, worker errors).
    System,
}

/// One line of task output shown in the log view.
#[derive(Debug, Clone)]
pub(crate) struct LogLine {
    /// Where the line came from.
    pub(crate) kind: LogKind,
    /// Line text without the trailing newline.
    pub(crate) text: String,
}
